# config for JSON fundamentals ingestion
general:
   verboseout: False
   includetext: True # switch to determine whether text fields are included in model
   on_colab: False
   debug_on: True
   master_date_mode: True # switch to determine whether start and end of timeframe controlled by master_start and master_end
   master_start: '2020-08-01' # if master_date_mode set to True, then timeframe is master_start -> master_end
   master_end: '2021-08-10'
   eod_token: "605766cf49ac93.89487471"
   eod_historical_token: "605766cf49ac93.89487471"
   
exchange_json_list:
- 'dja_2021-10-28.json'

indicator_list:
- 'real_interest_rate'
- 'population_total'
- 'net_trades_goods_services'
- 'net_migration'
- 'life_expectancy'
- 'internet_users_per_hundred'
- 'mobile_subscriptions_per_hundred'


etf_list:
- 'IYW'
- 'IYH'
- 'IYF'
- 'XLY'
- 'IYZ'
- 'IYJ'
- 'VDC'
- 'IYE'
- 'IDU'
- 'IYR'
- 'IYM'
- 'URTH'
- 'SPY'
- 'QQQ'
- 'VTI'
- 'VGT'
- 'VHT'
- 'VFH'
- 'VCR'
- 'XLC'
- 'VIS'
- 'IYK'
- 'VDE'
- 'VPU'
- 'VNQ'
- 'VAW'
- 'QWLD'
- 'VOO'
- 'IWV'

# files and directories
files:
   saved_model_modifier: January312021
   sector_ticker: sector_ticker.csv
   multi_parm_file: test_multi_parm_sep4.csv
   fundamentals_directory: static_load_fundamentals_gsptse
#   fundamentals_directory: static_load_fundamentals
   tse_test: "https://drive.google.com/file/d/1lAXY00O_tmsoch1SeisEF-EcYEIRyM3j/view?usp=sharing"
tech_list:
- 'GE'
- 'IBM'
- 'GOOGL'
#- 'ARNC'
# - 'ASML'
#   - 'KWR'
static_load:
   static_feature_list: ['gdp', 'cpi', 'oil_price'] # features that are loaded from saved repository
   static_load_start: '2002-10-01' # start date for the static load
   static_load_end: '2021-04-01' # end date for the static load
hyperparameters:
   learning_rate: 0.001
   dropout_rate: 0.0003 #0.003
   l2_lambda: 0.0003 #7.5
   loss_func: "binary_crossentropy"
   output_activation: "hard_sigmoid" # set to "linear" if target is continuous
   batch_size: 1000
   epochs: 50