general:
   verboseout: False
   includetext: True # switch to determine whether text fields are included in model
   on_colab: False
   debug_on: False
   presaved: False # switch to determine whether to train model or load saved model
   savemodel: False # switch to determine whether to save model
   picklemodel: True # switch for code to allow pickling of Keras model
   save_model_plot: False
   tensorboard_callback: False
   hctextmax: 7000
   maxwords: 6000
   textmax: 50
   pickled_data_file: '20142018_0930.pkl'
   pickled_dataframe: 'AB_NYC_2019_output_aug19_2020.pkl'
   modifier: 'oct05_2020'
   targetthresh: 6.0 # use as boundary between delay and no delay
   targetcontinuous: False # switch to determine whether target is continuous
   target_col: 'price'
   emptythresh: 6000
   zero_weight: 1.0 # class_weight = {0 : zero_weight, 1: one_weight}
   one_weight: 45.878 # default one_weight
   one_weight_offset: 0 # additional offset to one_weight
   patience_threshold: 3
   min_max_norm: True # switch to determine whether to use min_max (True) or standardization (False)
   master_date_mode: True # switch to determine whether start and end of timeframe controlled by master_start and master_end
   master_start: '2007-10-01' # if master_date_mode set to True, then timeframe is master_start -> master_end
   master_end: '2020-09-01'
   repeatable_run: False # switch to control whether runs are repeated identically
   years_window: 2 # if master_date_mode set to False then timeframe is [current date - years_window] -> current date
   max_years_back: 20 # maximum years back from present year that the timeframe can be defined for
   training_proportion: 0.8 # proportion of timeframe to use to train the model
   close_threshold: 0.01
   report_round: 4
   ust_cols: ['2 YR']
   quandl_token: "uCghYBw8CtpUvWct_W8c"
   finnhumb_key: "c16hj0f48v6ppg7erf7g"
   eod_token: "OeAFFmMliFG5orCUuwAKQ8l4WWFQ67YX"
   look_back: 20 # number of days back used to predict subsequent day being predicted
   look_ahead: 40 # gap in days between last of training data and first day being predicted
   look_ahead_scale: 0.5 # proportion of prediction timeframe to use for lookahead if lookahead > prediction timeframe
   multi_parm_run: True # switch to determine whether to read multi_parm_file to get sets of parameters
   # if multi_parm_run = True, read multi_parm_file and for each row in it, do an iteration with the parms set from that row of the file
   # if multi_parm_run = False, just do one iteration using parms from the config file
   #lstm_target: 'Close' # this is the target of the model - the value being predicted
   lstm_target: 'Close'
#   feature_list: []
#  FULL LIST OF FEATURES: ['2 YR','30 YR', 'Sector_Close','VIX','URTH', 'personal_sav_rate', 'oil_price', 'schiller_ratio', 'consumer_sentiment','public_debt', 'Bullish', 'Bearish', 'gdp', 'cpi', 'unemployment']
# MAY 6 pre list: ['2 YR','10 YR','30 YR','Bullish','Bearish','unemployment','gdp','cpi','Sector_Close','VIX']
   feature_list: ['2 YR','30 YR', 'VIX','personal_sav_rate', 'oil_price', 'schiller_ratio', 'consumer_sentiment','public_debt', 'Bullish', 'Bearish', 'gdp', 'cpi', 'unemployment']
files:
   saved_model_modifier: January312021
   sector_ticker: sector_ticker.csv
   multi_parm_file: test_multi_parm_may15.csv
tech_list:
- 'GE'
#- 'IBM'
#- 'ARNC'
# - 'ASML'
#   - 'KWR'
hyperparameters:
   learning_rate: 0.001
   dropout_rate: 0.0003 #0.003
   l2_lambda: 0.0003 #7.5
   loss_func: "binary_crossentropy"
   output_activation: "hard_sigmoid" # set to "linear" if target is continuous
   batch_size: 1000
   epochs: 50