general:
   verboseout: False
   includetext: True # switch to determine whether text fields are included in model
   on_colab: False
   debug_on: True
   presaved: False # switch to determine whether to train model or load saved model
   savemodel: False # switch to determine whether to save model
   picklemodel: True # switch for code to allow pickling of Keras model
   save_model_plot: False
   tensorboard_callback: False
   hctextmax: 7000
   maxwords: 6000
   textmax: 50
   pickled_data_file: '20142018_0930.pkl'
   pickled_dataframe: 'AB_NYC_2019_output_aug19_2020.pkl'
   modifier: 'oct05_2020'
   targetthresh: 6.0 # use as boundary between delay and no delay
   targetcontinuous: False # switch to determine whether target is continuous
   target_col: 'price'
   emptythresh: 6000
   zero_weight: 1.0 # class_weight = {0 : zero_weight, 1: one_weight}
   one_weight: 45.878 # default one_weight
   one_weight_offset: 0 # additional offset to one_weight
   patience_threshold: 3
   main_fundamentals_switch: True
   min_max_norm: True # switch to determine whether to use min_max (True) or standardization (False)
   master_date_mode: True # switch to determine whether start and end of timeframe controlled by master_start and master_end
   master_start: '2016-05-01' # if master_date_mode set to True, then timeframe is master_start -> master_end
   master_end: '2021-05-01'
   repeatable_run: False # switch to control whether runs are repeated identically
   years_window: 2 # if master_date_mode set to False then timeframe is [current date - years_window] -> current date
   max_years_back: 20 # maximum years back from present year that the timeframe can be defined for
   training_proportion: 0.8 # proportion of timeframe to use to train the model
   close_threshold: 0.01
   report_round: 4
   ust_cols: ['2 YR']
   quandl_token: "uCghYBw8CtpUvWct_W8c"
   finnhumb_key: "c16hj0f48v6ppg7erf7g"
   rapidai_key: "d747b1fadamsh1d7ce49966b2dffp161862jsnab3680125c9e"
   eod_token: "OeAFFmMliFG5orCUuwAKQ8l4WWFQ67YX"
   fmpcloud_key: "8b8f188c549c0399d2679fbf974a0a9f"
   eod_historical_token: "6057885c018fd9.09873427"
   marketstack_key : '619472d1ffefe4e9c494e77be6266dae'
   look_back: 20 # number of days back used to predict subsequent day being predicted
   look_ahead: 20 # gap in days between last of training data and first day being predicted
   look_ahead_scale: 0.5 # proportion of prediction timeframe to use for lookahead if lookahead > prediction timeframe
   xgboost_solo: True
   multi_parm_run: False # switch to determine whether to read multi_parm_file to get sets of parameters
   # if multi_parm_run = True, read multi_parm_file and for each row in it, do an iteration with the parms set from that row of the file
   # if multi_parm_run = False, just do one iteration using parms from the config file
   #lstm_target: 'Close' # this is the target of the model - the value being predicted
   lstm_target: 'Close'
#   feature_list: []
#  FULL LIST OF FEATURES: ['2 YR','30 YR', 'Sector_Close','VIX','URTH',us_dollar_index', 'personal_sav_rate', 'oil_price', 'schiller_ratio', 'consumer_sentiment','public_debt', 'Bullish', 'Bearish', 'gdp', 'cpi', 'unemployment']
# MAY 6 pre list: ['2 YR','10 YR','30 YR','Bullish','Bearish','unemployment','gdp','cpi','Sector_Close','VIX']
# NOTE: post Aug 10, URTH is just treated as another ticker and VIX is removed
   feature_list: ['2 YR','us_dollar_index', 'personal_sav_rate', 'oil_price', 'schiller_ratio', 'consumer_sentiment','public_debt', 'Bullish', 'Bearish', 'gdp', 'cpi', 'unemployment','non_farm','m2_money','st_louis','volume']
   fundamentals_feature_list: [
'Financials_Income_Statement_quarterly_totalRevenue',
'Financials_Income_Statement_quarterly_operatingIncome',
'Financials_Cash_Flow_quarterly_netIncome',
'Financials_Cash_Flow_quarterly_changeInCash',
'Financials_Cash_Flow_quarterly_dividendsPaid',
'Financials_Balance_Sheet_quarterly_cash',
'Earnings_History_epsActual',
'outstandingShares_shares']
# features that can be loaded in an automated way
   conventional_feature_list: ['us_dollar_index','public_debt','personal_sav_rate', 'oil_price', 'schiller_ratio', 'consumer_sentiment','gdp', 'cpi', 'unemployment', 'non_farm','m2_money','st_louis']
   ticker_feature_list: ['volume']
# quandl keys for conventional features
conventional_feature_keys:
   us_dollar_index: "FRED/TWEXBANL"
   public_debt: "FRED/GFDEGDQ188S"
   personal_sav_rate: "FRED/PSAVERT"
   oil_price: "FRED/DCOILWTICO"
   schiller_ratio: "MULTPL/SHILLER_PE_RATIO_MONTH"
   consumer_sentiment: "UMICH/SOC1"
   gdp: "FRED/GDP"
   cpi: "FRED/CPIAUCSL"
   unemployment: "FRED/UNRATE"
   non_farm: "FRED/PAYEMS"
   m2_money: "FRED/M2V"
   st_louis: "FRED/STLFSI"
files:
   saved_model_modifier: January312021
   sector_ticker: sector_ticker.csv
   multi_parm_file: test_multi_parm_sep4.csv
   json_fundamentals_mockup: json_fundamentals_mockup.csv
   current_fundamentals_directory: fundamentals_gprc
tech_list:
- 'ABCB'
#- 'ARNC'
# - 'ASML'
#   - 'KWR'
static_load:
   static_feature_list: ['gdp', 'cpi', 'oil_price'] # features that are loaded from saved repository
   static_load_start: '2002-10-01' # start date for the static load
   static_load_end: '2021-04-01' # end date for the static load
hyperparameters:
   learning_rate: 0.001
   dropout_rate: 0.0003 #0.003
   l2_lambda: 0.0003 #7.5
   loss_func: "binary_crossentropy"
   output_activation: "hard_sigmoid" # set to "linear" if target is continuous
   batch_size: 1000
   epochs: 50